# Cible pour exécuter les migrations
migrate:
	python3 manage.py migrate

# Cible pour lancer le serveur de développement
runserver:
	python3 manage.py runserver

# Cible pour exécuter les migrations et lancer le serveur
start: migrate runserver
